# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- github-pages
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jemoji

# Set theme
remote_theme: daviddarnes/alembic@main

# Site settings
url: 'open-econ.org'
baseurl: ''
title: 'Open Source Economics'
description: 'A platform for transdisciplinary collaboration'
permalink: pretty
#logo: "/assets/images/OSE_Bonn_sbrg_web.svg"
logo: "/assets/images/OSE_logo_RGB.svg"
#favicon: "/favicon.ico"

# Header nav
navigation_header:
- title: About
  url: /
- title: Tools
  url: /tools/
- title: Workflow
  url: /workflow/
- title: Models
  url: /models/
- title: People
  url: /people/
  
# Footer nav
navigation_footer:
- title: Contact us
  url: "https://ose.zulipchat.com/"
