# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- github-pages
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jemoji

# Set theme
remote_theme: daviddarnes/alembic@main

# Site settings
url: 'open-econ.org'
#url: 'OpenSourceEconomics.github.io'
baseurl: ''
title: 'Open Source Economics'
description: 'A platform for transdisciplinary collaboration'
permalink: pretty
#logo: "/assets/images/OSE_Bonn_sbrg_web.svg"
logo: "/assets/images/OSE_logo_RGB.svg"
#favicon: "/favicon.ico"
google_analytics: 'UA-188554161-1'

# Header nav
navigation_header:
- title: About
  url: /
- title: Software
  url: /software/
- title: Events
  url: /events/
- title: Resources
  url: /resources/
- title: Research
  url: /research/
- title: Education
  url: /education/
- title: Jobs
  url: /jobs/
  
# Footer nav
navigation_footer:
- title: Contact us
  url: "mailto:info@open-econ.org"
