# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jemoji
- jekyll-remote-theme

# Site settings
url: 'OpenSourceEconomics.github.io'
baseurl: ''
title: 'OpenSourceEconomics'
description: 'A platform for transdisciplinary collaboration'
permalink: pretty
#logo: "/assets/images/OSE_bonn_clean.svg"
#logo: "/assets/images/OSE_bonn_mdli.svg"
logo: "/assets/images/OSE_bonn_sbrg.svg"
#favicon: "/favicon.ico"

# Header nav
navigation_header:
- title: About
  url: /
- title: Software
  url: /software/
- title: Events
  url: /events/
- title: Resources
  url: /resources/

# Footer nav
navigation_footer:
- title: Contact us
  url: "mailto:info@open-econ.org"
